# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CudaDevice": "CUDA_GPU_Management.ipynb",
         "CudaHandler": "CUDA_GPU_Management.ipynb",
         "split_df": "bilstm-based-search-on-netflix-data.ipynb",
         "Vocab": "bilstm-based-search-on-netflix-data.ipynb",
         "seqData": "bilstm-based-search-on-netflix-data.ipynb",
         "arrData": "bilstm-based-search-on-netflix-data.ipynb",
         "fuse": "bilstm-based-search-on-netflix-data.ipynb",
         "Node": "dataframe_pipeline.ipynb",
         "chunkNode": "dataframe_pipeline.ipynb",
         "frameEdge": "dataframe_pipeline.ipynb",
         "colEdge": "dataframe_pipeline.ipynb",
         "donothing": "dataframe_pipeline.ipynb",
         "nothing": "dataframe_pipeline.ipynb",
         "fillNaEdge": "dataframe_pipeline.ipynb",
         "engTokEdge": "dataframe_pipeline.ipynb",
         "CNTok": "dataframe_pipeline.ipynb",
         "capMinMaxEdge": "dataframe_pipeline.ipynb",
         "trackVocabEdge": "dataframe_pipeline.ipynb",
         "saveCSV": "dataframe_pipeline.ipynb",
         "saveSQL": "dataframe_pipeline.ipynb",
         "eng_twt_tk": "dataframe_pipeline.ipynb",
         "to_optim": "imports.ipynb",
         "__all__": "imports.ipynb",
         "Path.ls": "imports.ipynb",
         "torch.nn.Module.to_optim": "imports.ipynb",
         "Opts": "optimizers.ipynb"}

modules = ["ftorch/cuda.py",
           "data/nlp.py",
           "pipe.py",
           "imports.py",
           "ftorch/optimizer.py"]

doc_url = "https://raynardj.github.io/forgebox/"

git_url = "https://github.com/raynardj/forgebox/tree/master/"

def custom_doc_links(name): return None
