# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://raynardj.github.io/forgebox/"

git_url = "https://github.com/raynardj/forgebox/tree/master/"

def custom_doc_links(name): return None
