# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/create_different.ipynb (unless otherwise specified).

__all__ = ['different_file_func']

# Comes from test_nbdev.ipynb, cell

def different_file_func():
    return 100