# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/imports.ipynb (unless otherwise specified).

__all__ = ['to_optim', '__all__']

# Cell

__all__ = ["pd","np","partial","Path","json","Counter",
           "plt","os","sys","glob","Image",]
import pandas as pd

pd.DataFrame.vc = lambda self,col:pd.DataFrame(self[col].value_counts())

import numpy as np
from pathlib import Path
import json
from functools import partial
from collections import Counter
from matplotlib import pyplot as plt

import os
import sys

try:
    import torch
    from torch import nn
    from torch.utils.data.dataset import Dataset
    from torch.utils.data.dataloader import DataLoader
    __all__+=["nn","torch","Dataset","DataLoader"]
except:
    print("""Pytorch not loaded""")

try:
    from torchvision import transforms as tfm
    __all__.append("tfm")
except:
    print("""Torch Vision not loaded""")

try:
    from ipywidgets import interact, interact_manual
    from IPython.display import HTML
    __all__+=["interact","interact_manual","HTML"]
except:
    print("Jupyter notebook libs not loaded")

from glob import glob
from PIL import Image

Path.ls = lambda x:os.listdir(x)

def to_optim(self,optimizer = torch.optim.Adam,**kwargs):
    self.optimizer = optimizer(self.parameters(),**kwargs)

torch.nn.Module.to_optim=to_optim
__all__.append("to_optim")