# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/imports.ipynb (unless otherwise specified).

__all__ = []

# Cell

import pandas as pd
import numpy as np
from pathlib import Path
import json
from functools import partial
from collections import Counter
from matplotlib import pyplot as plt
import os
import sys
import torch
from torch import nn
from torch.utils.data.dataset import Dataset
from torch.utils.data.dataloader import DataLoader
from torchvision import transforms as tfm
from ipywidgets import interact, interact_manual
from IPython.display import HTML

from glob import glob
from PIL import Image

Path.ls = lambda x:os.listdir(x)
