# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/11_train.ipynb (unless otherwise specified).

__all__ = ['DataLoop', 'BeforeBatch', 'BeforeForward', 'BeforeForward']

# Cell
from .loop import Loop,Event,method4all,StorageCore

class DataLoop(Loop):
    def __init__(self,dataloader):
        super().__init__(iterable=dataloader)

class BeforeBatch(Event):
    def __init__(self,):
        super().__init__(self,event_name = "before_batch")

class BeforeForward(Event):
    def __init__(self,):
        super().__init__(self,event_name = "before_forward")

class BeforeForward(Event):
    def __init__(self,):
        super().__init__(self,event_name = "before_forward")