# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/21_minimum.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .config import Config
from datetime import datetime
from uuid import uuid4
from inspect import getargspec
from copy import deepcopy